Repository atomist/samples, pull requests merged in 2019-06, with the labels that each got.

#15 Add testing support for SDMs
  lib/sdm/dotnetCore.ts
  package-lock.json
  package.json
  test/empty.test.ts
  test/sdm/dotnetCore.test.ts
  test/sdm/mockConfigure.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#17 Extract some functions for clarity
  index.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#18 Move code from docs so I can reference it
  README.md
  lib/command/helloWorld.ts
Labels: auto-merge-method:squash, auto-merge:on-approve

#16 Add Maven sample and extra tests
  README.md
  lib/sdm/jenkinsJob.ts
  lib/sdm/maven.ts
  package-lock.json
  package.json
  test/sdm/dotnetCore.test.ts
  test/sdm/jenkinsJob.test.ts
  test/sdm/maven.test.ts
  test/sdm/mockConfigure.ts
  test/sdm/testSupport.ts
Labels: auto-merge-method:squash, auto-merge:on-approve, auto-rebase:on-push, changelog:added

#28 Add container goal samples
  README.md
  lib/sdm/container/0goal.ts
  lib/sdm/container/1parallel.ts
  lib/sdm/container/2node-maven.ts
  lib/sdm/container/3cache.ts
  lib/sdm/container/4callback.ts
  lib/sdm/container/5volumes.ts
  package-lock.json
  package.json
Labels: auto-merge-method:merge, auto-merge:on-approve
